# Generated by Django 3.1.3 on 2020-11-12 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отыет')),
                ('correct', models.BooleanField(verbose_name='Правильность')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('nick', models.CharField(max_length=100, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('avatar', models.ImageField(max_length=1024, upload_to='', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='QuestionsLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(null=True, verbose_name='Отметка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questions')),
            ],
            options={
                'verbose_name': 'Лайки вопроса',
                'verbose_name_plural': 'Лайки вопросов',
            },
        ),
        migrations.AddField(
            model_name='questions',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(to='app.Tags'),
        ),
        migrations.CreateModel(
            name='AnswersLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(null=True, verbose_name='Отметка')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.answers')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
            options={
                'verbose_name': 'Лайки ответа',
                'verbose_name_plural': 'Лайки ответов',
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questions'),
        ),
    ]
