# Generated by Django 3.1.3 on 2020-11-13 21:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201113_1804'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tags',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='answers',
            name='text',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tags'),
        ),
    ]
