# Generated by Django 3.1.3 on 2020-11-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201113_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Правильность'),
        ),
    ]
