# Generated by Django 3.1.3 on 2020-11-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201114_1013'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tags',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='/27804.png', max_length=1024, upload_to='', verbose_name='Аватар'),
        ),
    ]
