# Generated by Django 3.1.3 on 2020-11-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201116_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(db_index=True, max_length=1024, verbose_name='Тег'),
        ),
    ]
