# Generated by Django 3.1.3 on 2020-11-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201116_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Тег'),
        ),
    ]
